const CREATE_PHONE_REQUEST = 'CREATE_PHONE_REQUEST';
const CREATE_PHONE_SUCCESS = 'CREATE_PHONE_SUCCESS';
const CREATE_PHONE_FAILURE = 'CREATE_PHONE_FAILURE';

const READ_PHONE_REQUEST = 'READ_PHONE_REQUEST';
const READ_PHONE_SUCCESS = 'READ_PHONE_SUCCESS';
const READ_PHONE_FAILURE = 'READ_PHONE_FAILURE';

const SELECT_PHONE = 'SELECT_PHONE';

const READ_UPDATE_PHONE_REQUEST = 'READ_UPDATE_PHONE_REQUEST';
const READ_UPDATE_PHONE_SUCCESS = 'READ_UPDATE_PHONE_SUCCESS';
const READ_UPDATE_PHONE_FAILURE = 'READ_UPDATE_PHONE_FAILURE';

const UPDATE_PHONE_REQUEST = 'UPDATE_PHONE_REQUEST';
const UPDATE_PHONE_SUCCESS = 'UPDATE_PHONE_SUCCESS';
const UPDATE_PHONE_FAILURE = 'UPDATE_PHONE_FAILURE';

const CHANGE_READ_UPDATE_PHONE = 'CHANGE_READ_UPDATE_PHONE';

const READ_DELETE_PHONE_REQUEST = 'READ_DELETE_PHONE_REQUEST';
const READ_DELETE_PHONE_SUCCESS = 'READ_DELETE_PHONE_SUCCESS';
const READ_DELETE_PHONE_FAILURE = 'READ_DELETE_PHONE_FAILURE';

const DELETE_PHONE_REQUEST = 'DELETE_PHONE_REQUEST';
const DELETE_PHONE_SUCCESS = 'DELETE_PHONE_SUCCESS';
const DELETE_PHONE_FAILURE = 'DELETE_PHONE_FAILURE';

export default {
    CREATE_PHONE_REQUEST,
    CREATE_PHONE_SUCCESS,
    CREATE_PHONE_FAILURE,

    READ_PHONE_REQUEST,
    READ_PHONE_SUCCESS,
    READ_PHONE_FAILURE,

    SELECT_PHONE,

    READ_UPDATE_PHONE_REQUEST,
    READ_UPDATE_PHONE_SUCCESS,
    READ_UPDATE_PHONE_FAILURE,

    UPDATE_PHONE_REQUEST,
    UPDATE_PHONE_SUCCESS,
    UPDATE_PHONE_FAILURE,

    CHANGE_READ_UPDATE_PHONE,

    READ_DELETE_PHONE_REQUEST,
    READ_DELETE_PHONE_SUCCESS,
    READ_DELETE_PHONE_FAILURE,

    DELETE_PHONE_REQUEST,
    DELETE_PHONE_SUCCESS,
    DELETE_PHONE_FAILURE,
};